export const ACTION_TYPES = {
  CHANGE_INPUT: "CHANGE_INPUT",
  FOCUS_INPUT: "FOCUS_INPUT",
  BLUR_INPUT: "BLUR_INPUT",
  SUBMIT_FORM: "SUBMIT_FORM",
  SHOW_ERRORS: "SHOW_ERRORS",
  RESET_FORM: "RESET_FORM",
  CLOSE_POPUP: "CLOSE_POPUP",
};
